#ifndef CX_VERSION_H_
#define CX_VERSION_H_

#define CX_VERSION_MAJOR 1
#define CX_VERSION_MINOR 0
#define CX_VERSION_RELEASE 0

#define CX_VERSION CX_VERSION_MAJOR.CX_VERSION_MINOR.CX_VERSION_RELEASE

#define CX_QUOTE(str) #str
#define CX_EXPAND(str) CX_QUOTE(str)
#define CX_VERSION_STRING CX_EXPAND(CX_VERSION)

#define CX_VERSION_NUMBER \
    (CX_VERSION_MAJOR * 100 * 100 + CX_VERSION_MINOR * 100 + CX_VERSION_RELEASE)

#endif
